base_url = "https://dirtybits.xyz"
title = "dirty bits"
default_language = "en"
compile_sass = true
minify_html = true
generate_feeds = true

[markdown]
highlight_code = true
generate_feed = true

[extra]
