base_url = "https://andrelcmoreira.me"
title = "andrelcmoreira"
default_language = "en"
compile_sass = true
minify_html = true
generate_feeds = true
author = "André"

[markdown]
highlight_code = true

[extra]
